apiVersion: operator.openshift.io/v1alpha1
kind: Kueue
metadata:
  labels:
    app.kubernetes.io/name: kueue-operator
    app.kubernetes.io/managed-by: kustomize
  name: cluster
  namespace: openshift-kueue-operator
spec:
  managementState: Managed
  config:
    integrations:
      frameworks:
      - AppWrapper
    gangScheduling:
      policy: None
    workloadManagement:
      labelPolicy: None
    preemption:
      preemptionPolicy: FairSharing
