apiVersion: operator.openshift.io/v1alpha1
kind: Kueue
metadata:
  labels:
    app.kubernetes.io/name: kueue-operator
    app.kubernetes.io/managed-by: kustomize
  name: cluster
  namespace: openshift-kueue-operator
spec:
  managementState: Managed
  config:
    integrations:
      frameworks:
      - RayJob
      - RayCluster
      - AppWrapper
      - PyTorchJob
    gangScheduling:
      policy: ByWorkload
      byWorkload: Parallel
    workloadManagement:
      labelPolicy: QueueNameRequired
    preemption:
      preemptionPolicy: Classical
