apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: kueue-metrics
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: kueue
    control-plane: controller-manager
  name: kueue-controller-manager-metrics-service
  namespace: openshift-kueue-operator
spec:
  ports:
  - name: metrics
    port: 8443
    targetPort: metrics
    protocol: TCP
  selector:
    control-plane: controller-manager
